### ISSUE TITLE
Can't connect to mobile services with latest version of this client

### ISSUE THREAD

**Issue by atsats** [Azure/azure-mobile-apps-cordova-client#11]
I had a working application and I removed and re-added the plugin and now the application can no longer connect. What has changed?

Fiddler reports the following header from the client on the connect:
```
X-ZUMO-VERSION: ZUMO/2.0 (lang=Cordova; os=--; os_version=--; arch=--; version=2.0.0-beta5-40404.165320)
Content-Type: application/json
```

And here's the server response:

`{"message":"No API version was specified in the request, this request needs to specify a ZUMO-API-VERSION of '2.0.0'.  For more information and supported clients see: http://go.microsoft.com/fwlink/?LinkId=690568#2.0.0"}`

What can be done to remedy this? Should I revert to an older working version?

**Comment by shrishrirang** [comment]
What is the API you are using when you are seeing this changed behavior? Is it invokeApi? I will have a look to check if a bug was inadvertently introduced. Meanwhile, can you use the plugin from npm (`cordova plugin add cordova-plugin-ms-azure-mobile-apps`) instead of the one from GitHub that you are currently using? The current HEAD of the GitHub repository and npm are functionally identical.

**Comment by atsats** [comment]
I've already reverted to the March 2nd Beta4 version and the program is working again. I believe this was happening on the API that accesses this URL:

`https://<mobile-site-address>/push/installations/`

I'm not exactly sure which one that is.

**Comment by shrishrirang** [comment]
Ok great, so that is Push. I'll update the plugin today.

**Comment by shrishrirang** [comment]
https://github.com/Azure/azure-mobile-apps-cordova-client/pull/13 fixes https://github.com/Azure/azure-mobile-apps-cordova-client/issues/11
